
name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install


  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Simular despliegue con marca de versión
        run: |
          mkdir -p production
          cp src/index.js production/
          echo "✅ App desplegada en entorno de producción:"
          ls -l production
