
  name: CI Pipeline

  on:
    push:
      branches: ["main"]

  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: Clonar repositorio
          uses: actions/checkout@v3

        - name: Instalar dependencias
          run: npm install

        - name: Ejecutar pruebas
          run: npm test
